pom.xml
=> refactor: change to alpha version

openapi/src/main/kotlin/com/expediagroup/sdk/generators/openapi/OpenApiSdkGenerator.kt
Changing the templates directory name to openworld-sdk
=> fix: Change the directory name

openapi/src/main/resources/templates/openworld-sdk/pom.mustache
=> build: Increasing the pom version

openapi/src/main/resources/templates/openworld-sdk/api.mustache, openapi/src/main/resources/templates/openworld-sdk/pom.mustache
=> feat: supporting default auth url

.github/workflows/generate-sdk-actions.yml
Adding an additional job to update the BOM version
=> build: adding an additional job to update the bom version

openapi/src/main/resources/templates/openworld-sdk/pom.mustache
build: Increasing the core version
=> build: Increasing the core version

.github/workflows/generate-sdk-actions.yml
fix: Fixing auto BOM update workflow by adding the full SDK name
=> fix: Fixing auto BOM update workflow by adding the full SDK name

.github/workflows/github-build-action.yml
build: Adding new github build stage action
=> build: Adding new github build stage action

openapi/src/main/resources/templates/openworld-sdk/pom.mustache
feat: Supporting dokka gfm generation
=> feat: Supporting dokka gfm generation

openapi/src/main/resources/templates/openworld-sdk/pom.mustache
chore: removing shading plugin from pom.mustache file
=> chore: removing shading plugin from pom.mustache file

openapi/src/main/resources/templates/openworld-sdk/pom.mustache
fix: removing Dokka from the install stage
=> fix: removing Dokka from the install stage

.github/workflows/generate-sdk-action.yml, openapi/src/main/resources/templates/openworld-sdk/api.mustache, openapi/src/main/resources/templates/openworld-sdk/enum_class.mustache
fix: Fixing license info issue when generating on Ubuntu OS
=> fix: Fixing licence info issue when generating on Ubuntu OS

openapi/src/main/resources/templates/openworld-sdk/data_class.mustache
=> chore: Adding static method for Builder pattern

openapi/src/main/resources/templates/openworld-sdk/api.mustache
- Add SDK language to User-Agent header
N/A
=> chore(rapid): Add SDK Language To User-Agent Header

openapi/pom.xml, openapi/src/main/resources/templates/openworld-sdk/api.mustache, openapi/src/main/resources/templates/openworld-sdk/pom.mustache, pom.xml
Make use of the new OpenWorld exceptions and update dependencies to fix the build.
N/A
**NOTE**: This depends on Open World Java Core 0.04: https://github.com/ExpediaGroup/openworld-sdk-java-core/pull/58
=> chore(error-handling): Throw OpenWorld Exceptions and Update Dependencies to fix the Build

openapi/src/main/kotlin/com/expediagroup/sdk/generators/openapi/Constant.kt
Fix a Naming Bug in Yaml Processor
N/A
=> Fix a Naming Bug

openapi/pom.xml, openapi/src/main/resources/templates/openworld-sdk/pom.mustache, pom.xml
Release 2022-12-06 Changes: Update Parent POM and Core Versions
N/A
=> Update Parent POM and Core Versions

.github/workflows/main-sdk-action.yml, openapi/pom.xml, openapi/src/main/resources/templates/openworld-sdk/pom.mustache, pom.xml
Bump Core and Parent POM versions up
N/A
=> chore(release): Bump Core and Parent POM versions up

.github/workflows/main-sdk-action.yml
=> feat(generation): Publish Generated SDK

pom.xml
Separate Generators POM from the Parent POM
N/A
---
Please verify that:
=> chore(pom): Separate Generators POM from the Parent POM

pom.xml
Update URLs in Generators POM
N/A
---
Please verify that:
=> fix(pom): Update URLs in Generators POM

openapi/src/main/resources/templates/openworld-sdk/api.mustache, openapi/src/main/resources/templates/openworld-sdk/pom.mustache
Refer to CONTRIBUTING.md for more details.
-->
- Use the new RapidClientConfig for Rapid clients
N/A
=> feat(rapid): Use The New RapidClientConfig For Rapid Clients

openapi/pom.xml, openapi/src/main/resources/templates/openworld-sdk/pom.mustache
Separate OpenAPI Generator POM from the Parent POM
N/A
---
=> chore(pom): Separate OpenAPI Generator POM from the Parent POM

openapi/src/main/resources/templates/openworld-sdk/pom.mustache
Separate Generated SDK Client POM from the Parent POM
N/A
---
Please verify that:
=> chore(pom): Separate Generated SDK Client POM from the Parent POM

openapi/src/main/resources/templates/openworld-sdk/pom.mustache
- Add a release profile.
- Add missing POM fields (URL, and description).
- Upgrade Used Core Version (`0.4.0` to `0.5.0`).
N/A
---
=> chore(build): Fix Release Issues & Upgrade Core

.github/workflows/main-sdk-action.yml
Please verify that:
- Remove extra published directories
N/A
=> chore(github): Remove Extra Published Directories

openapi/src/main/resources/templates/openworld-sdk/pom.mustache
- Upgrade Core version to 0.6.0
N/A
=> chore(upgrade): Upgrade Core Version

openapi/src/main/resources/templates/openworld-sdk/api.mustache
- Add builder pattern to client
N/A
=> chore(generation): Add Builder Pattern to Client

openapi/src/main/resources/templates/openworld-sdk/api.mustache
- Fix builder pattern for client
N/A
=> fix(generation): Fix Builder Pattern for Client

openapi/src/main/resources/templates/openworld-sdk/api.mustache
- Make `builder` function static
N/A
=> fix(generation): Make `builder` Function Static

openapi/src/main/resources/templates/openworld-sdk/pom.mustache
=> chore(build): Upgrade Core Version

.github/workflows/commit.yml, .github/workflows/generate.yml, .github/workflows/main.yml, .github/workflows/prepare_version.yml
=> chore: update release actions

openapi/src/main/resources/templates/openworld-sdk/pom.mustache
=> chore: format generated code

openapi/src/main/resources/templates/openworld-sdk/pom.mustache
=> chore(dependencies): Upgrade Dokka Version

openapi/src/main/resources/templates/openworld-sdk/paginator.mustache
- Make paginationTotalResults final
N/A
=> fix(generation): Make paginationTotalResults Final
